// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

import {FhishType} from "./FhishType.sol";
import "./IFhishCoprocessor.sol";

/**
 * @title   FhishConfigStruct
 * @notice  This struct contains all addresses of core contracts, which are needed in a typical dApp.
 */
struct FhishConfigStruct {
    address ACLAddress;
    address FhishExecutorAddress;
    address KMSVerifierAddress;
    address InputVerifierAddress;
}

/**
 * @title   DecryptionRequestsStruct
 * @notice  This struct contains the address of the decryption oracle contract,
 *          the internal counter for requestIDs generated by the dapp,
 *          and the mapping from internal requestIDs to list of handles requested for decryption.
 */
struct DecryptionRequestsStruct {
    address DecryptionOracleAddress;
    uint256 counterRequest;
    mapping(uint256 => bytes32[]) requestedHandles;
}

/**
 * @title   IFhishCoprocessor
 * @notice  This interface contains all functions to conduct FHE operations.
 */
interface IACL {
    function allowTransient(bytes32 ciphertext, address account) external;
    function allow(bytes32 handle, address account) external;
    function cleanTransientStorage() external;
    function isAllowed(bytes32 handle, address account) external view returns (bool);
    function allowForDecryption(bytes32[] memory handlesList) external;
    function isAllowedForDecryption(bytes32 handle) external view returns (bool);
}

interface IInputVerifier {
    function cleanTransientStorage() external;
}

library FhishImpl {
    bytes32 private constant FhishConfigLocation = 0xed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea600;
    bytes32 private constant DecryptionRequestsStorageLocation = 0x5ea69329017273582817d320489fbd94f775580e90c092699ca6f3d12fdf7d00;

    function getFhishConfig() internal pure returns (FhishConfigStruct storage $) {
        assembly { $.slot := FhishConfigLocation }
    }

    function getDecryptionRequests() internal pure returns (DecryptionRequestsStruct storage $) {
        assembly { $.slot := DecryptionRequestsStorageLocation }
    }

    function setCoprocessor(FhishConfigStruct memory config) internal {
        FhishConfigStruct storage $ = getFhishConfig();
        $.ACLAddress = config.ACLAddress;
        $.FhishExecutorAddress = config.FhishExecutorAddress;
        $.KMSVerifierAddress = config.KMSVerifierAddress;
        $.InputVerifierAddress = config.InputVerifierAddress;
    }

    function setDecryptionOracle(address decryptionOracle) internal {
        DecryptionRequestsStruct storage $ = getDecryptionRequests();
        $.DecryptionOracleAddress = decryptionOracle;
    }

    function add(bytes32 lhs, bytes32 rhs, bool scalar) internal returns (bytes32 result) {
        bytes1 scalarByte = scalar ? bytes1(0x01) : bytes1(0x00);
        FhishConfigStruct storage $ = getFhishConfig();
        result = IFhishCoprocessor($.FhishExecutorAddress).fheAdd(lhs, rhs, scalarByte);
    }

    function sub(bytes32 lhs, bytes32 rhs, bool scalar) internal returns (bytes32 result) {
        bytes1 scalarByte = scalar ? bytes1(0x01) : bytes1(0x00);
        FhishConfigStruct storage $ = getFhishConfig();
        result = IFhishCoprocessor($.FhishExecutorAddress).fheSub(lhs, rhs, scalarByte);
    }

    function mul(bytes32 lhs, bytes32 rhs, bool scalar) internal returns (bytes32 result) {
        bytes1 scalarByte = scalar ? bytes1(0x01) : bytes1(0x00);
        FhishConfigStruct storage $ = getFhishConfig();
        result = IFhishCoprocessor($.FhishExecutorAddress).fheMul(lhs, rhs, scalarByte);
    }

    function div(bytes32 lhs, bytes32 rhs) internal returns (bytes32 result) {
        FhishConfigStruct storage $ = getFhishConfig();
        result = IFhishCoprocessor($.FhishExecutorAddress).fheDiv(lhs, bytes32(0), bytes1(0x01)); // Placeholder
    }

    function min(bytes32 lhs, bytes32 rhs, bool scalar) internal returns (bytes32 result) {
        bytes1 scalarByte = scalar ? bytes1(0x01) : bytes1(0x00);
        FhishConfigStruct storage $ = getFhishConfig();
        result = IFhishCoprocessor($.FhishExecutorAddress).fheMin(lhs, rhs, scalarByte);
    }

    function max(bytes32 lhs, bytes32 rhs, bool scalar) internal returns (bytes32 result) {
        bytes1 scalarByte = scalar ? bytes1(0x01) : bytes1(0x00);
        FhishConfigStruct storage $ = getFhishConfig();
        result = IFhishCoprocessor($.FhishExecutorAddress).fheMax(lhs, rhs, scalarByte);
    }

    function bitAnd(bytes32 l, bytes32 r) internal returns (bytes32) { return IFhishCoprocessor(getFhishConfig().FhishExecutorAddress).fheBitAnd(l, r, bytes1(0x00)); }
    function bitOr(bytes32 l, bytes32 r) internal returns (bytes32) { return IFhishCoprocessor(getFhishConfig().FhishExecutorAddress).fheBitOr(l, r, bytes1(0x00)); }
    function bitXor(bytes32 l, bytes32 r) internal returns (bytes32) { return IFhishCoprocessor(getFhishConfig().FhishExecutorAddress).fheBitXor(l, r, bytes1(0x00)); }
    function shl(bytes32 l, uint8 bits) internal returns (bytes32) { return IFhishCoprocessor(getFhishConfig().FhishExecutorAddress).fheShl(l, bytes32(uint256(bits)), bytes1(0x01)); }
    function shr(bytes32 l, uint8 bits) internal returns (bytes32) { return IFhishCoprocessor(getFhishConfig().FhishExecutorAddress).fheShr(l, bytes32(uint256(bits)), bytes1(0x01)); }

    function randBounded(uint256 upper, FhishType t) internal returns (bytes32) { return IFhishCoprocessor(getFhishConfig().FhishExecutorAddress).fheRandBounded(upper, t); }
    function randBoundedSeeded(uint256 upper, bytes32 seed, FhishType t) internal returns (bytes32) {
        (bool ok, bytes memory data) = getFhishConfig().FhishExecutorAddress.call(
            abi.encodeWithSignature("fheRandBoundedSeeded(uint256,bytes32,uint8)", upper, seed, uint8(t))
        );
        require(ok, "rand seeded failed");
        return abi.decode(data, (bytes32));
    }

    function eq(bytes32 lhs, bytes32 rhs, bool scalar) internal returns (bytes32 result) {
        bytes1 scalarByte = scalar ? bytes1(0x01) : bytes1(0x00);
        FhishConfigStruct storage $ = getFhishConfig();
        result = IFhishCoprocessor($.FhishExecutorAddress).fheEq(lhs, rhs, scalarByte);
    }

    function ne(bytes32 lhs, bytes32 rhs, bool scalar) internal returns (bytes32 result) {
        bytes1 scalarByte = scalar ? bytes1(0x01) : bytes1(0x00);
        FhishConfigStruct storage $ = getFhishConfig();
        result = IFhishCoprocessor($.FhishExecutorAddress).fheNe(lhs, rhs, scalarByte);
    }

    function ge(bytes32 lhs, bytes32 rhs, bool scalar) internal returns (bytes32 result) {
        bytes1 scalarByte = scalar ? bytes1(0x01) : bytes1(0x00);
        FhishConfigStruct storage $ = getFhishConfig();
        result = IFhishCoprocessor($.FhishExecutorAddress).fheGe(lhs, rhs, scalarByte);
    }

    function gt(bytes32 lhs, bytes32 rhs, bool scalar) internal returns (bytes32 result) {
        bytes1 scalarByte = scalar ? bytes1(0x01) : bytes1(0x00);
        FhishConfigStruct storage $ = getFhishConfig();
        result = IFhishCoprocessor($.FhishExecutorAddress).fheGt(lhs, rhs, scalarByte);
    }

    function le(bytes32 lhs, bytes32 rhs, bool scalar) internal returns (bytes32 result) {
        bytes1 scalarByte = scalar ? bytes1(0x01) : bytes1(0x00);
        FhishConfigStruct storage $ = getFhishConfig();
        result = IFhishCoprocessor($.FhishExecutorAddress).fheLe(lhs, rhs, scalarByte);
    }

    function lt(bytes32 lhs, bytes32 rhs, bool scalar) internal returns (bytes32 result) {
        bytes1 scalarByte = scalar ? bytes1(0x01) : bytes1(0x00);
        FhishConfigStruct storage $ = getFhishConfig();
        result = IFhishCoprocessor($.FhishExecutorAddress).fheLt(lhs, rhs, scalarByte);
    }

    function select(bytes32 control, bytes32 ifTrue, bytes32 ifFalse) internal returns (bytes32 result) {
        FhishConfigStruct storage $ = getFhishConfig();
        result = IFhishCoprocessor($.FhishExecutorAddress).fheIfThenElse(control, ifTrue, ifFalse);
    }

    function verify(bytes32 inputHandle, bytes memory inputProof, FhishType toType) internal returns (bytes32 result) {
        FhishConfigStruct storage $ = getFhishConfig();
        // CALL REAL PRECOMPILE/INPUT VERIFIER
        // Zama v2 pattern: verifyCiphertext on the executor/coprocessor
        result = IFhishCoprocessor($.FhishExecutorAddress).verifyCiphertext(inputHandle, msg.sender, inputProof, toType);
        
        // ALLOW TRANSIENT (for this txn)
        IACL($.ACLAddress).allowTransient(result, msg.sender);
    }

    function trivialEncrypt(uint256 value, FhishType toType) internal returns (bytes32 result) {
        FhishConfigStruct storage $ = getFhishConfig();
        result = IFhishCoprocessor($.FhishExecutorAddress).trivialEncrypt(value, toType);
    }

    function allow(bytes32 handle, address account) internal {
        FhishConfigStruct storage $ = getFhishConfig();
        IACL($.ACLAddress).allow(handle, account);
    }

    function allowTransient(bytes32 handle, address account) internal {
        FhishConfigStruct storage $ = getFhishConfig();
        IACL($.ACLAddress).allowTransient(handle, account);
    }

    function isAllowed(bytes32 handle, address account) internal view returns (bool) {
        FhishConfigStruct storage $ = getFhishConfig();
        return IACL($.ACLAddress).isAllowed(handle, account);
    }

    event DecryptionRequested(bytes32 indexed handle, address requester);

    function decrypt(bytes32 handle) internal returns (uint256) {
        FhishConfigStruct storage $ = getFhishConfig();
        emit DecryptionRequested(handle, msg.sender);
        
        DecryptionRequestsStruct storage reqStruct = getDecryptionRequests();
        if (reqStruct.DecryptionOracleAddress != address(0)) {
            bytes32[] memory handles = new bytes32[](1);
            handles[0] = handle;
            reqStruct.requestedHandles[reqStruct.counterRequest] = handles;
            reqStruct.counterRequest++;
        }
        
        return 0;
    }
}
